package thoniyil.sridaran.musicgenerator.music;

public enum Interval
{
	MINOR_SECOND, MAJOR_SECOND, MINOR_THIRD, MAJOR_THIRD, PERFECT_FOURTH,
	DIMINISHED_FIFTH, PERFECT_FIFTH, MINOR_SIXTH, MAJOR_SIXTH, MINOR_SEVENTH, MAJOR_SEVENTH,
	PERFECT_OCTAVE, MINOR_NINTH, MAJOR_NINTH, MINOR_TENTH, MAJOR_TENTH, MINOR_ELEVENTH, MAJOR_ELEVENTH;
	
	public int getSemiTones()
	{
		return ordinal() + 1;
	}
}
